import { PREFIXES, MAX_ENTRY_LENGTH } from "../config";

import {
  prepareChangelogEntry,
  prepareChangelogEntriesMap,
  prepareChangesetEntriesContent,
  InvalidPrefixError,
  EmptyEntryDescriptionError,
  EntryTooLongError,
  ChangelogEntryMissingHyphenError,
} from "../utils";

describe("Formatting Utils Tests", () => {
  const prNumber = 123;
  const prLink = "http://example.com/pr/123";
  const descriptionText = "Test description";

  // This array of strings is returned by the extractChangelogEntries function in the workflow, provided the "Changelog" section of the PR description is valid.
  const changesetEntries = [
    "- feat: Adds one feature",
    "- fix: Fixes a bug",
    "- feat: Adds a second feature",
  ];

  describe("prepareChangelogEntry", () => {
    test.each(PREFIXES)(
      `correctly prepare changelog entry for "%s" prefix`,
      (prefix) => {
        const entry = `- ${prefix}: ${descriptionText}`;
        const expectedOutput =
          prefix === "skip"
            ? ""
            : `- ${
                descriptionText.charAt(0).toUpperCase() +
                descriptionText.slice(1)
              } ([#${prNumber}](${prLink}))`;
        expect(prepareChangelogEntry(entry, prNumber, prLink)).toEqual([
          expectedOutput,
          prefix,
        ]);
      }
    );

    test("with invalid prefix, should throw InvalidPrefixError", () => {
      const invalidPrefix = "invalid";
      const invalidEntry = `- ${invalidPrefix}: This is an invalid prefix`;
      const expectedErrorMessage = `Invalid description prefix. Found "${invalidPrefix}". Expected "breaking", "deprecate", "feat", "fix", "infra", "doc", "chore", "refactor", "security", "skip", or "test".`;

      expect(() => {
        prepareChangelogEntry(invalidEntry, prNumber, prLink);
      }).toThrow(InvalidPrefixError);
      expect(() => {
        prepareChangelogEntry(invalidEntry, prNumber, prLink);
      }).toThrow(expectedErrorMessage);
    });

    test("with empty entry description, should throw EmptyEntryDescriptionError", () => {
      const emptyDescriptionEntry = "- feat:";
      expect(() => {
        prepareChangelogEntry(emptyDescriptionEntry, prNumber, prLink);
      }).toThrow(EmptyEntryDescriptionError);
    });

    test("with entry too long, should throw EntryTooLongError", () => {
      const longEntryText =
        " a very long entry with too much text that exceeds the maximum allowed length";
      const longEntry = `- feat:${longEntryText}`;
      const characterOverage = longEntryText.length - MAX_ENTRY_LENGTH;
      const expectedErrorMessage = `Entry is ${
        longEntryText.length
      } characters long, which is ${characterOverage} ${
        characterOverage === 1 ? "character" : "characters"
      } longer than the maximum allowed length of ${MAX_ENTRY_LENGTH} characters.`;

      expect(() => {
        prepareChangelogEntry(longEntry, prNumber, prLink);
      }).toThrow(EntryTooLongError);
      expect(() => {
        prepareChangelogEntry(longEntry, prNumber, prLink);
      }).toThrow(expectedErrorMessage);
    });

    test("with entry missing hyphen, should throw ChangelogEntryMissingHyphenError", () => {
      const noHyphenEntry = "feat: Missing hyphen at start";
      expect(() => {
        prepareChangelogEntry(noHyphenEntry, prNumber, prLink);
      }).toThrow(ChangelogEntryMissingHyphenError);
    });
  });

  describe("prepareChangesetEntriesContent", () => {
    test("should return formatted content for the changeset file based on the entry map generated by prepareChangelogEntriesMap", () => {
      // Generate the entry map using prepareChangelogEntriesMap
      const entryMap = prepareChangelogEntriesMap(
        changesetEntries,
        prNumber,
        prLink,
        prepareChangelogEntry,
      );

      // Define the expected output
      const expectedContent =
        "feat:\n" +
        "- Adds one feature ([#123](http://example.com/pr/123))\n" +
        "- Adds a second feature ([#123](http://example.com/pr/123))\n\n" +
        "fix:\n" +
        "- Fixes a bug ([#123](http://example.com/pr/123))";

      // Call the function
      const actualContent = prepareChangesetEntriesContent(entryMap);

      // Assert the output
      expect(actualContent).toBe(expectedContent);
    });
  });

  describe("prepareChangelogEntriesMap", () => {
    test("should return an object with changeset entries categorized by their prefixes", () => {
      const expectedChangesetEntryMap = {
        feat: [
          "- Adds one feature ([#123](http://example.com/pr/123))",
          "- Adds a second feature ([#123](http://example.com/pr/123))",
        ],
        fix: [
          "- Fixes a bug ([#123](http://example.com/pr/123))",
        ],
      };

      const actualChangesetEntryMap = prepareChangelogEntriesMap(
        changesetEntries,
        prNumber,
        prLink,
        prepareChangelogEntry
      );

      expect(actualChangesetEntryMap).toEqual(expectedChangesetEntryMap);
    });
  });
});
